# HR Buddy Agents Configuration
agents:
  researcher:
    role: "Job Description Researcher"
    goal: "Extract job title, description, requirements, company, location, and other relevant information from the provided job posting URL."
    tools:
      - name: "web_scraper"
        type: "custom"
        config:
          url_template: "{job_url}"
          timeout: 10
          retries: 3
    communication:
      output_format: "dictionary"
      output_fields:
        - "title"
        - "description"
        - "requirements"
        - "company"
        - "location"
        - "posted_date"
      error_handling:
        retry_on_failure: true
        fallback_value: "N/A"

  social_media_profiler:
    role: "Social Media Profiler"
    goal: "Gather and structure information from social media profiles (LinkedIn, GitHub, etc.)."
    tools:
      - name: "social_media_scraper"
        type: "custom"
        config:
          api_endpoint: "https://api.socialmedia.com/v1/profile"
          api_key: "${SOCIAL_MEDIA_API_KEY}"  # Use environment variable for security
          rate_limit: 100
    communication:
      output_format: "dictionary"
      output_fields:
        - "work_experience"
        - "skills"
        - "education"
        - "contact_info"
        - "projects"
      error_handling:
        retry_on_failure: true
        fallback_value: "N/A"

  resume_strategist:
    role: "Resume Strategist"
    goal: "Generate a tailored resume based on the job posting data, social media profile data, and parsed resume data."
    tools:
      - name: "llm"
        type: "ollama"
        config:
          api_endpoint: "http://localhost:11434/api/generate"
          model_name: "deepseek"  # Updated for DeepSeek R1 1.5B
          temperature: 0.7
          max_tokens: 1000
      - name: "resume_generator"
        type: "custom"
        config:
          template_path: "templates/resume_template.docx"
          output_format: "pdf"
    communication:
      input_format: "dictionary"
      input_fields:
        - "job_data"
        - "social_profile"
        - "resume_data"
      output_format: "file"
      output_file_type: "pdf"
      error_handling:
        retry_on_failure: true
        fallback_action: "log_and_continue"

  interview_preparer:
    role: "Interview Preparer"
    goal: "Generate a list of targeted interview questions based on the job description and the candidate's resume."
    tools:
      - name: "llm"
        type: "ollama"
        config:
          api_endpoint: "http://localhost:11434/api/generate"
          model_name: "deepseek"  # Updated for DeepSeek R1 1.5B
          temperature: 0.5
          max_tokens: 500
    communication:
      input_format: "dictionary"
      input_fields:
        - "job_data"
        - "resume_data"
      output_format: "file"
      output_file_type: "pdf"
      error_handling:
        retry_on_failure: true
        fallback_action: "log_and_continue"

# Global Configuration
global_config:
  logging:
    level: "INFO"
    file_path: "logs/hr_buddy.log"
    rotation: "10MB"
  error_handling:
    max_retries: 3
    retry_delay: 5
