# HR Buddy Agents Configuration
agents:
  researcher:
    role: "Job Description Researcher"
    goal: "Extract job title, description, requirements, company, location, and other relevant information from the provided job posting URL."
    tools:
      - name: "web_scraper"
        type: "custom"
        config:
          url_template: "{job_url}"  # Template for dynamically inserting the job URL
          timeout: 10  # Timeout in seconds for the web scraper
          retries: 3   # Number of retries if scraping fails
    communication:
      output_format: "dictionary"
      output_fields:
        - "title"
        - "description"
        - "requirements"
        - "company"
        - "location"
        - "posted_date"
      error_handling:
        retry_on_failure: true
        fallback_value: "N/A"

  social_media_profiler:
    role: "Social Media Profiler"
    goal: "Find and extract structured information from social media profiles (LinkedIn, GitHub, etc.) using SerpAPI and scraping."
    tools:
      - name: "serpapi_scraper"
        type: "custom"
        config:
          api_endpoint: "https://serpapi.com/search"
          api_key: "YOUR_SERPAPI_KEY"  # Replace with actual API key
          search_template: "site:linkedin.com/in/ {name} {role}"
          search_template_github: "site:github.com {username}"
          rate_limit: 100
      - name: "linkedin_scraper"
        type: "custom"
        config:
          method: "selenium"
          login_required: true
          fields_to_extract:
            - "work_experience"
            - "skills"
            - "education"
            - "contact_info"
            - "projects" 
    communication:
      output_format: "dictionary"
      output_fields:
        - "work_experience"
        - "skills"
        - "education"
        - "contact_info"
        - "projects"
      error_handling:
        retry_on_failure: true
        fallback_value: "N/A"

  resume_strategist:
    role: "Resume Strategist"
    goal: "Generate a tailored resume based on job posting data, social media profile data, and parsed resume data."
    tools:
      - name: "deepseek_r1"
        type: "local_llm"
        config:
          model: "deepseek-r1-1.5b"
          runtime: "ollama"
          temperature: 0.7
          max_tokens: 1000
      - name: "resume_generator"
        type: "custom"
        config:
          template_path: "templates/resume_template.docx"
          output_format: "pdf"
          fields_to_replace:
            - "name"
            - "contact_info"
            - "work_experience"
            - "education"
            - "skills"
            - "projects"
    communication:
      input_format: "dictionary"
      input_fields:
        - "job_data"
        - "social_profile"
        - "resume_data"
      output_format: "file"
      error_handling:
        retry_on_failure: true
        fallback_action: "log_and_continue"

  interview_preparer:
    role: "Interview Preparer"
    goal: "Generate a list of targeted interview questions based on the job description and candidate's resume."
    tools:
      - name: "deepseek_r1"
        type: "local_llm"
        config:
          model: "deepseek-r1-1.5b"
          runtime: "ollama"
          temperature: 0.5
          max_tokens: 500
    communication:
      input_format: "dictionary"
      input_fields:
        - "job_data"
        - "resume_data"
      output_format: "file"
      error_handling:
        retry_on_failure: true
        fallback_action: "log_and_continue"

# Global Configuration
global_config:
  logging:
    level: "INFO"
    file_path: "logs/hr_buddy.log"
  error_handling:
    max_retries: 3
    retry_delay: 5
