researcher:
  role: "Job Description Researcher"
  goal: "Extract job title, description, requirements, company, location, and other relevant information from the provided job posting URL."
  tools:
    - name: "web_scraper"
      type: "custom"
      config:
        url_template: "{job_url}"
  communication:
    output_format: "dictionary"
    output_fields: ["title", "description", "requirements", "company", "location"]

social_media_profiler:
  role: "Social Media Profiler"
  goal: "Gather and structure information from social media profiles (LinkedIn, GitHub, etc.)."
  tools:
    - name: "social_media_scraper"
      type: "custom"
      config:
        # Add any necessary configuration for your social media scraping tool
  communication:
    output_format: "dictionary"
    output_fields: ["work_experience", "skills", "education", "contact_info"]

resume_strategist:
  role: "Resume Strategist"
  goal: "Generate a tailored resume based on the job posting data, social media profile data, and parsed resume data."
  tools:
    - name: "llm"
      type: "openai"
      config:
        api_key: "YOUR_LLM_API_KEY"
        model: "text-davinci-003"
    - name: "resume_generator"
      type: "custom"
      config:
        # Configuration for ResumeGeneratorTool
  communication:
    input_format: "dictionary"
    input_fields: ["job_data", "social_profile", "resume_data"]
    output_format: "file"  # Output is a PDF file

interview_preparer:
  role: "Interview Preparer"
  goal: "Generate a list of targeted interview questions based on the job description and the candidate's resume."
  tools:
    - name: "llm"
      type: "openai"
      config:
        api_key: "YOUR_LLM_API_KEY"
        model: "text-davinci-003"
  communication:
    input_format: "dictionary"
    input_fields: ["job_data", "resume_data"]
    output_format: "file"  # Output is a PDF file